project:
  type: website
  output-dir: docs
  resources:
    # - "robots.txt"
    # - "seven-wonders.pdf"
    - "palebluedotA4s.png"
    - "media"
    - "scripts"

strip-comments: true

crossref:
  fig-prefix: ""
  eq-prefix: ""
  sec-prefix: ""
  def-prefix: ""
  tbl-prefix: ""

number-depth: 2

callout-icon: false

date: last-modified
date-format: iso

website:
  bread-crumbs: false
  # date: today
  # date-format: iso
  open-graph: false
#  favicon: favicon.png
#  cover-image: ada511logo.png
  title: "The Seven Wonders of the World: Lecture notes on 21st-century physics"
  # author:
  #   - "P.G.L. Porta Mana [![ORCID](orcid_32x32.png){width=1em}](https://orcid.org/0000-0002-6070-0784) [{{< fa house >}}](https://portamana.org/)"
  reader-mode: true
  sidebar:
    # date-format: iso
    # date: 02-02-1902
    title: "The Seven Wonders of the World: Lecture notes on 21st-century physics"
#    logo: ada511logo8_small.png
    author:
      - name: P.G.L. Porta Mana
        orcid: 0000-0002-6070-0784
    style: "docked"
    collapse-level: 4
  # search:
  #   location: navbar
  #   type: overlay
  # navbar:
  #   pinned: true
  #   left:
  #   - index.qmd
    # - text.qmd
    
    # - part: "[**An invitation**]{.lightblue}"
    #   chapters:
    #     - intro.qmd
    #     - framework.qmd
    #     - basic_decisions.qmd

format:
  html:
    # self-contained-math: true
    # embed-resources: true
    theme: flatly
    link-external-icon: false
    link-external-newwindow: true
    ## flatly journal litera simplex
    # mainfont: "DejaVu Sans"
    # monofont: "DejaVu Sans Mono"
    css: seven-wonders-styles.css
    html-math-method: mathjax
    reference-location: margin
    citation-location: margin
    toc-location: right
    toc-expand: true
    email-obfuscation: references
    # include-in-header: mathjax.html
    # sidebar:
    #   date-format: iso
    #   date: last-modified
    #   title: "ADA511 [0.1]{.small .grey} <br>Data science and data-driven engineering <br>updated {{< meta date >}}"

filters:
  - mathpunctuation.lua
#  - center-images.lua

  # pdf:
  #   keep-tex: true
  #   documentclass: scrreprt
  #   papersize: a4
  #   header-includes:
  #   - \usepackage{mathtools}
  #   - \usepackage[normalem]{ulem}

execute:
  freeze: auto
  # keep-ipynb: true


